name: Check
on:
  pull_request:
permissions:
  contents: read
concurrency:
  group: check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
        with:
          content-read-key: ${{ secrets.CONTENT_READ_KEY }}
      - run: npm run check
